# site properties and page defaults
title: Genetics and Bioinformatics Department
subtitle: at Dasman Diabetes Institute
description: We use several genome-wide methodologies, including genome-wide association studies (GWAS), whole genome/exome sequencing, whole transcriptome profiling and high-resolution genotyping. We focus on identifying the clinical significance of the identified gene/variants to identify the best medical approach to treat diabetes. Our research includes investigating epigenomic alterations, gene-gene interactions, microRNA profiling and development of panels consisting of population-specific markers for predicting the risk outcomes of complex disorders.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: contact@GB-DDI.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: GB-DDI
  twitter: GB-DDI
  youtube: GB-DDI

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

url: https://gb-ddi.github.io
baseurl: /gb-website
